/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JFrame;

/**
 *
 * @author catalvasfa_sd2022
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public AdminDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_ViewMed = new javax.swing.JButton();
        jButton_OrderMed = new javax.swing.JButton();
        jLabel_LOGOUT = new javax.swing.JLabel();
        jButton_RemoveMed = new javax.swing.JButton();
        jButton_AddMed = new javax.swing.JButton();
        jButton_UpdateMed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(241, 169, 160));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PHARMACIST");

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClose.setText("x");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClose)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelClose)
                        .addComponent(jLabelMin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 60);

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));

        jButton_ViewMed.setBackground(new java.awt.Color(34, 167, 240));
        jButton_ViewMed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_ViewMed.setText("VIEW MEDICINE");
        jButton_ViewMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ViewMedMouseClicked(evt);
            }
        });
        jButton_ViewMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewMedActionPerformed(evt);
            }
        });

        jButton_OrderMed.setBackground(new java.awt.Color(52, 152, 219));
        jButton_OrderMed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_OrderMed.setText("ORDER MEDICINE");
        jButton_OrderMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_OrderMedMouseClicked(evt);
            }
        });
        jButton_OrderMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OrderMedActionPerformed(evt);
            }
        });

        jLabel_LOGOUT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_LOGOUT.setForeground(java.awt.Color.white);
        jLabel_LOGOUT.setText("Click here to logout");
        jLabel_LOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LOGOUTMouseClicked(evt);
            }
        });

        jButton_RemoveMed.setBackground(new java.awt.Color(34, 167, 240));
        jButton_RemoveMed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_RemoveMed.setText("REMOVE MEDICINE");
        jButton_RemoveMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_RemoveMedMouseClicked(evt);
            }
        });
        jButton_RemoveMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveMedActionPerformed(evt);
            }
        });

        jButton_AddMed.setBackground(new java.awt.Color(34, 167, 240));
        jButton_AddMed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_AddMed.setText("ADD MEDICINE");
        jButton_AddMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AddMedMouseClicked(evt);
            }
        });
        jButton_AddMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddMedActionPerformed(evt);
            }
        });

        jButton_UpdateMed.setBackground(new java.awt.Color(34, 167, 240));
        jButton_UpdateMed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_UpdateMed.setText("UPDATE MEDICINE");
        jButton_UpdateMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_UpdateMedMouseClicked(evt);
            }
        });
        jButton_UpdateMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateMedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_AddMed, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_RemoveMed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_OrderMed, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ViewMed, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_UpdateMed, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel_LOGOUT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_OrderMed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_RemoveMed, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ViewMed, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AddMed, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton_UpdateMed, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jLabel_LOGOUT)
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 490, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButton_ViewMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ViewMedMouseClicked
        ViewMed viewmed = new ViewMed ();
        viewmed.setVisible(true);
        viewmed.pack();
        viewmed.setLocationRelativeTo(null);

        viewmed.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_ViewMedMouseClicked

    private void jButton_ViewMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewMedActionPerformed

    }//GEN-LAST:event_jButton_ViewMedActionPerformed

    private void jButton_OrderMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_OrderMedMouseClicked
        OrderMed ordermed = new OrderMed ();
        ordermed.setVisible(true);
        ordermed.pack();
        ordermed.setLocationRelativeTo(null);

        ordermed.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_OrderMedMouseClicked

    private void jButton_OrderMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OrderMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_OrderMedActionPerformed

    private void jLabel_LOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LOGOUTMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_LOGOUTMouseClicked

    private void jButton_RemoveMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RemoveMedMouseClicked
        RemoveMed removemed = new RemoveMed ();
        removemed.setVisible(true);
        removemed.pack();
        removemed.setLocationRelativeTo(null);
        
        removemed.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_RemoveMedMouseClicked

    private void jButton_RemoveMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RemoveMedActionPerformed

    private void jButton_AddMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AddMedMouseClicked
        AddMed addmed = new AddMed ();
        addmed.setVisible(true);
        addmed.pack();
        addmed.setLocationRelativeTo(null);
        
        addmed.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_AddMedMouseClicked

    private void jButton_AddMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddMedActionPerformed

    private void jButton_UpdateMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_UpdateMedMouseClicked
        RemoveMed removemed = new RemoveMed ();
        removemed.setVisible(true);
        removemed.pack();
        removemed.setLocationRelativeTo(null);
        
        removemed.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_UpdateMedMouseClicked

    private void jButton_UpdateMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_UpdateMedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddMed;
    private javax.swing.JButton jButton_OrderMed;
    private javax.swing.JButton jButton_RemoveMed;
    private javax.swing.JButton jButton_UpdateMed;
    private javax.swing.JButton jButton_ViewMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabel_LOGOUT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
